//! The names of the tools, and the argument names the callers share. A tool is
//! called by its name, so the runtime, the windows and the browser page all use
//! these and none spells a name twice.

pub const TOOL_OBSERVE: &str = "observe";
pub const TOOL_LOOK_AROUND: &str = "look_around";
pub const TOOL_FIND_MOBILES: &str = "find_mobiles";
pub const TOOL_FIND_ITEMS: &str = "find_items";
pub const TOOL_FIND_LANDMARKS: &str = "find_landmarks";
pub const TOOL_JOURNAL_SEARCH: &str = "journal_search";
pub const TOOL_MAP_TILE: &str = "map_tile";
pub const TOOL_CAN_WALK: &str = "can_walk";
pub const TOOL_LINE_OF_SIGHT: &str = "line_of_sight";
pub const TOOL_PROMPT_ANSWER: &str = "prompt_answer";
pub const TOOL_PARTY: &str = "party";
pub const TOOL_ROUTE: &str = "route";
pub const TOOL_MOBILE_STATUS: &str = "mobile_status";
pub const TOOL_PROMPT_CANCEL: &str = "prompt_cancel";
pub const TOOL_SAY: &str = "say";
pub const TOOL_WHISPER: &str = "whisper";
pub const TOOL_REPLY: &str = "reply";
pub const TOOL_EMOTE: &str = "emote";
pub const TOOL_MOVE_TO: &str = "move_to";
pub const TOOL_WALK: &str = "walk";
pub const TOOL_OPEN_DOOR: &str = "open_door";
pub const TOOL_FOLLOW: &str = "follow";
pub const TOOL_STOP: &str = "stop";
pub const TOOL_LOGOUT: &str = "logout";
pub const TOOL_USE: &str = "use";
pub const TOOL_SINGLE_CLICK: &str = "single_click";
pub const TOOL_ATTACK: &str = "attack";
pub const TOOL_WAR_MODE: &str = "war_mode";
pub const TOOL_LIFT: &str = "lift";
pub const TOOL_DROP: &str = "drop";
pub const TOOL_EQUIP: &str = "equip";
pub const TOOL_UNEQUIP: &str = "unequip";
pub const TOOL_CAST: &str = "cast";
pub const TOOL_USE_SKILL: &str = "use_skill";
pub const TOOL_WAIT_TARGET: &str = "wait_target";
pub const TOOL_WAIT_JOURNAL: &str = "wait_journal";
pub const TOOL_NEXT_EVENT: &str = "next_event";
pub const TOOL_TARGET: &str = "target";
pub const TOOL_OPEN_CONTAINER: &str = "open_container";
pub const TOOL_LOOT: &str = "loot";
pub const TOOL_DEPOSIT: &str = "deposit";
pub const TOOL_TRADE_OFFER: &str = "trade_offer";
pub const TOOL_TRADE_ACCEPT: &str = "trade_accept";
pub const TOOL_TRADE_CANCEL: &str = "trade_cancel";
pub const TOOL_VENDOR_SELL: &str = "vendor_sell";
pub const TOOL_VENDOR_BUY: &str = "vendor_buy";
pub const TOOL_CONTEXT_MENU: &str = "context_menu";
pub const TOOL_GUMP_RESPOND: &str = "gump_respond";
pub const TOOL_GUMP_CLOSE: &str = "gump_close";
pub const TOOL_SET_GOAL: &str = "set_goal";
pub const TOOL_CANCEL_GOAL: &str = "cancel_goal";
pub const TOOL_SET_PERSONA: &str = "set_persona";
pub const TOOL_RUN_SCRIPT: &str = "run_script";
pub const TOOL_STOP_SCRIPT: &str = "stop_script";
pub const TOOL_SCRIPT_STATUS: &str = "script_status";
pub const TOOL_LIST_SCRIPTS: &str = "list_scripts";
pub const TOOL_SCRIPT_READ: &str = "script_read";
pub const TOOL_SCRIPT_SAVE: &str = "script_save";
pub const TOOL_MAP_PIN: &str = "map_pin";
pub const TOOL_MAP_CLOSE: &str = "map_close";
pub const TOOL_PROFILE: &str = "profile";
pub const TOOL_HOUSE_EDIT: &str = "house_edit";
pub const TOOL_HELP: &str = "help";
pub const TOOL_CHAT: &str = "chat";
pub const TOOL_BOOK_WRITE: &str = "book_write";
pub const TOOL_AGENTS: &str = "agents";
pub const TOOL_AGENT_SET: &str = "agent_set";
pub const TOOL_AGENT_ON: &str = "agent_on";
pub const TOOL_AGENT_RUN: &str = "agent_run";
pub const TOOL_AGENT_STOP: &str = "agent_stop";
pub const TOOL_DAMAGE_METER: &str = "damage_meter";
pub const TOOL_TARGET_FILTER: &str = "target_filter";
pub const TOOL_HOTKEYS: &str = "hotkeys";
pub const TOOL_HOTKEY: &str = "hotkey";
pub const TOOL_RECORD_MACRO: &str = "record_macro";
pub const TOOL_JOBS: &str = "jobs";
pub const TOOL_JOB_START: &str = "job_start";
pub const TOOL_JOB_STOP: &str = "job_stop";
/// The watch window puts this in the arguments of each call a human makes.
pub const ARG_HUMAN: &str = "human";
pub const TOOL_WATCH: &str = "watch";
pub const TOOL_PROPERTIES: &str = "properties";
pub const TOOL_CLOSE_MENU: &str = "close_menu";
pub const TOOL_SHOP_CHECKOUT: &str = "shop_checkout";
pub const TOOL_SHOP_CLOSE: &str = "shop_close";
pub const TOOL_DYE: &str = "dye";
pub const TOOL_MENU_PICK: &str = "menu_pick";
pub const TOOL_BOOK_CLOSE: &str = "book_close";
pub const TOOL_BOARD_READ: &str = "board_read";
pub const TOOL_BOARD_POST: &str = "board_post";
pub const TOOL_BOARD_REMOVE: &str = "board_remove";
pub const TOOL_BOARD_CLOSE: &str = "board_close";
pub const TOOL_TRADE_GOLD: &str = "trade_gold";
pub const TOOL_COMMAND: &str = "command";
pub const TOOL_TAKE_CONTROL: &str = "take_control";
pub const TOOL_RELEASE_CONTROL: &str = "release_control";
pub const TOOL_GAME_VIEW: &str = "game_view";
pub const TOOL_OPEN_SPELLBOOK: &str = "open_spellbook";
pub const TOOL_TIP: &str = "tip";
pub const TOOL_QUEST_ARROW: &str = "quest_arrow";
pub const TOOL_BOAT_MOVE: &str = "boat_move";
pub const TOOL_TRACK_MEMBERS: &str = "track_members";
pub const TOOL_HOUSE_CONTENT: &str = "house_content";
pub const TOOL_RACE_CHANGE: &str = "race_change";
pub const TOOL_BOOK_READ: &str = "book_read";
pub const TOOL_FIND_TILES: &str = "find_tiles";
pub const TOOL_MULTI_PARTS: &str = "multi_parts";
pub const TOOL_FIND_ENTRANCES: &str = "find_entrances";
pub const TOOL_VIRTUE: &str = "virtue";
pub const TOOL_VIRTUE_GUMP: &str = "virtue_gump";
pub const TOOL_SKILL_LOCK: &str = "skill_lock";
pub const TOOL_STAT_LOCK: &str = "stat_lock";
pub const TOOL_RENAME: &str = "rename";
pub const TOOL_SET_ABILITY: &str = "set_ability";
pub const TOOL_EMOTE_ACTION: &str = "emote_action";
pub const TOOL_FLY: &str = "fly";
pub const TOOL_MENU_BUTTON: &str = "menu_button";
pub const TOOL_TARGET_RESOURCE: &str = "target_resource";
pub const TOOL_USE_TYPE: &str = "use_type";
pub const TOOL_USE_ON: &str = "use_on";
pub const TOOL_CATCH_BAG: &str = "catch_bag";
pub const TOOL_MOUNT: &str = "mount";
pub const TOOL_DISMOUNT: &str = "dismount";
pub const TOOL_ATTACK_NEAREST: &str = "attack_nearest";
pub const TOOL_IGNORE_LIST: &str = "ignore_list";
pub const TOOL_SKILL_GAINS: &str = "skill_gains";
pub const TOOL_LANDMARKS_INFO: &str = "landmarks_info";
pub const TOOL_CONNECT: &str = "connect";
pub const TOOL_DISCONNECT: &str = "disconnect";
pub const TOOL_CHARACTERS: &str = "characters";
pub const TOOL_CHARACTER_CREATE: &str = "character_create";
pub const TOOL_CHARACTER_DELETE: &str = "character_delete";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_watch_tool_keeps_its_name() {
        assert_eq!(TOOL_WATCH, "watch");
        assert_eq!(ARG_HUMAN, "human");
    }
}
